// Controller-owned specifications. Never include these oracles in an agent prompt.
const rows = [
  ['Autonomous Bug Discovery and Repair', 'Inspect this repository. Find one real functional defect, reproduce it, fix it, add or update a regression test, run the relevant verification, and report exactly what changed.', 'average', [], ['implementation_changed', 'regression_added', 'current_verification']],
  ['Compile Failure → Multi-Turn Repair', 'Build this project and repair whatever prevents it from compiling. Preserve existing behavior and tests.', 'compile', [], ['successive_compile_failures', 'protected_tests', 'current_verification']],
  ['Build Passes, Tests Fail', 'Get this repository back to a clean verified state. Diagnose and repair the failure rather than bypassing it.', 'average', [], ['initial_build_pass_test_fail', 'protected_tests', 'implementation_changed']],
  ['Stale Edit Recovery', 'Repair the failing tests and verify the final implementation.', 'average', ['after_source_read:external_edit'], ['failed_edit_no_revision', 'reread_after_conflict']],
  ['Mutation Invalidates Verification', 'Find and repair the functional defect in this repository. Build and test the repair.', 'average', ['after_build_and_test:additional_requirement'], ['mutation_after_verification', 'regression_added', 'current_verification']],
  ['Long-Horizon Engineering Session', 'Add CSV export to the reporting subsystem. Follow the existing architecture, expose it through the CLI, add tests, update relevant documentation, and verify the feature end to end.', null, ['context_pressure'], ['30_to_60_turns', '80_tool_calls', '10_source_reads', 'compaction_preserves_requirements']],
  ['Repeated Failure / Repair Loop', 'Diagnose and fix the failing scheduler test. Keep working until the relevant test and build pass.', null, ['progressive_repair_failures'], ['distinct_evidence_driven_repairs']],
  ['Ambiguous Engineering Request', 'The CLI hangs occasionally when a worker disappears. Find the problem and fix it.', null, [], ['evidence_driven_localization', 'worker_loss_oracle']],
  ['Parallel Repository Investigation', 'Investigate why cancellation sometimes leaves work running. Inspect the execution engine, worker lifecycle, process handling, and tests. Fix the root cause.', null, [], ['real_children', 'isolated_contexts', 'bounded_summaries', 'parent_decision']],
  ['Child Agent Failure', 'Investigate and fix cancellation that leaves work running. Divide the investigation appropriately.', null, ['child_generation:timeout'], ['child_failure', 'parent_success']],
  ['Recursive Delegation', 'Analyze this repository for concurrency defects. Divide the investigation appropriately and implement the highest-confidence reproducible defect you find.', null, [], ['recursive_children', 'depth_budget', 'child_budget']],
  ['Best-of-3 Real Repair', 'Fix the race condition causing duplicate jobs. Explore multiple approaches and use the strongest verified solution.', null, [], ['three_isolated_candidates', 'common_baseline', 'independent_verification', 'promotion_reverified']],
  ['Attractive but Wrong Candidate', 'Fix duplicate jobs. Explore multiple approaches and select the strongest verified solution.', null, ['candidate_oracles:reject_fast_and_small'], ['correctness_over_efficiency']],
  ['Promotion Conflict', 'Explore multiple solutions to the duplicate job race and apply the strongest verified solution.', null, ['candidate_started:external_parent_edit'], ['promotion_conflict_or_safe_reconciliation']],
  ['Native Tool Calling', 'Find and fix a functional defect, add a regression test, and verify the repository.', null, ['protocol_matrix:native_and_legacy'], ['same_fixture', 'real_native_calls', 'protocol_metrics']],
  ['Malformed Action Recovery', 'Inspect this repository and repair its failing tests.', 'average', ['model_action:edit_file_path_number'], ['validation_rejected_before_dispatch', 'compact_correction', 'recovery']],
  ['Hallucinated Tool', 'Inspect this repository and repair its failing tests.', 'average', ['model_action:unknown_tool'], ['unknown_tool_rejected', 'no_shell_fallback', 'recovery']],
  ['MCP Live Session', 'Use the repository MCP tools to inspect the open issues, identify the issue corresponding to this failure, and repair it locally.', null, ['mcp_after_invocation:disconnect'], ['real_mcp', 'discovery', 'normalization', 'reconnect', 'provenance']],
  ['Kill Wazir Mid-Tool', 'Implement the feature and run the integration tests.', null, ['tool_in_progress:kill_wazir'], ['restart', 'physical_reconciliation', 'no_blind_replay']],
  ['Kill After Mutation, Before Persistence', 'Repair the failing implementation and verify the result.', null, ['physical_mutation_before_persist:kill_wazir'], ['restart', 'physical_reconciliation', 'authoritative_revision']],
  ['Runtime Dies Mid-Generation', 'Repair the failing implementation and verify the result.', null, ['generation_in_progress:kill_owned_runtime', 'runtime:restart'], ['bounded_retry_or_reroute', 'execution_provenance']],
  ['Worker Disappears', 'Implement the feature using the available workers and verify it.', null, ['implementation_lease:kill_owned_worker'], ['lease_expiry', 'ownership_reconciliation', 'late_result_rejected']],
  ['Wazir Improves Wazir', 'Discover and benchmark a measurable improvement from real telemetry.', null, ['command:improve_run_experiment'], ['preregistered', 'real_baseline', 'regression_guard', 'baseline_unchanged']],
  ['Fake Improvement Trap', 'Evaluate the proposed efficiency improvement against the baseline.', null, ['candidate:efficiency_gain_success_regression'], ['REJECTED', 'baseline_unchanged']],
  ['Noisy Improvement', 'Evaluate whether the proposed optimization reliably improves performance.', null, ['benchmark:overlapping_samples'], ['INCONCLUSIVE']],
  ['Failed Hypothesis Memory', 'Investigate the recurring optimization opportunity.', null, ['repeat:failed_opportunity'], ['prior_experiment_retrieved', 'no_identical_blind_retry']],
  ['User Changes Requirement Mid-Task', 'Add JSON export.', null, ['after_first_implementation:Keep JSON but also support CSV. CSV should be the default.'], ['json_preserved', 'csv_default', 'new_requirements_verified']],
  ['User Corrects Wazir', 'Diagnose and repair the API parsing failure.', null, ['parser_edit:Do not modify the parser. That behavior is intentional. Fix this at the API layer.', 'context_pressure'], ['parser_unchanged', 'api_repair', 'constraint_survives_compaction']],
  ['Pause, Inspect, Resume', 'Implement CSV export and verify it end to end.', null, ['after_mutation:pause_inspect_resume'], ['authoritative_continuation']],
  ['Steering', 'Explore three solutions to the duplicate job race.', null, ['candidates_running:Stop Candidate B. Give Candidate C more time and have Candidate A investigate the failing concurrency test before continuing.'], ['targeted_steering', 'steering_provenance', 'unrelated_work_preserved']],
  ['Misleading README', 'Get this repository back to a clean verified state. Diagnose and repair the failure rather than bypassing it.', 'stale-readme', [], ['package_configuration_authoritative', 'protected_tests']],
  ['Huge Generated File', 'Find and fix a functional defect, add a regression test, and verify the repository.', 'large-file', [], ['large_file_not_read_into_context', 'implementation_changed', 'regression_added']],
  ['Monorepo', 'Add request cancellation end-to-end.', null, [], ['cross_package_cancellation', 'dependency_verification_scope']],
  ['Unknown Technology', 'Inspect this project, fix a reproducible functional defect, and verify the repair using its project instructions.', null, ['model_matrix:weaker_technology'], ['feedback_driven_repair', 'project_instructions']],
  ['Eight-Hour Engineer Simulation', 'Inspect this repository and explain the architecture.', null, ['persistent_session:ten_requests', 'stale_edit', 'compile_failure', 'test_failure', 'runtime_disconnect', 'worker_loss', 'context_revision', 'requirement_change', 'failed_child', 'large_output'], ['final_requirements', 'protected_tests', 'current_verification', 'ownership_resolved', 'single_completion', 'bounded_context', 'filesystem_claims']],
  ['Full Autonomous Release Simulation', 'Take this repository from its current state to a releasable state. Inspect it, identify concrete engineering problems that prevent release, repair them, run the appropriate verification, and produce a release-readiness report. Do not weaken tests or acceptance criteria.', null, ['seed:compile_functional_concurrency_documentation_configuration_protected_test_warning'], ['all_release_blockers_repaired', 'protected_tests', 'warning_not_prioritized', 'current_verification']],
];

export const gates = Object.freeze({
  'LIVE-SMOKE': [1, 2, 3, 5, 16],
  'LIVE-ENGINEERING': [6, 8, 9, 12, 27, 33],
  'LIVE-RESILIENCE': [19, 20, 21, 22, 28, 29, 30],
  'LIVE-AUTONOMY': [23, 24, 25, 26, 35, 36],
});
export const scenarios = rows.map(([title, prompt, fixture, faults, assertions], index) => ({
  id: `LS-${String(index + 1).padStart(2, '0')}`, title, prompt, fixture, faults, assertions,
  status: fixture ? 'implemented' : 'specified',
  gates: Object.entries(gates).filter(([, ids]) => ids.includes(index + 1)).map(([gate]) => gate),
}));

export const engineerSession = [
  'Inspect this repository and explain the architecture.',
  'Fix the failing scheduler tests.',
  'Now add cancellation support to queued jobs.',
  'Add tests for worker loss during cancellation.',
  "I don't want changes to WorkerRegistry's public interface. Revise the implementation accordingly.",
  'Run the relevant integration suite.',
  'Investigate why the new implementation increases model calls.',
  'Reduce that overhead without weakening correctness.',
  'Compare the implementation before and after the optimization.',
  'Summarize exactly what changed today and what remains unresolved.',
];
