#!/usr/bin/env bash
# Install Wazir from source: deps, build, and put `wa` on PATH.
#
# Safe to run from any directory — it locates the repo from its own path.
# The `wa` launcher is installed as a shim in ~/.local/bin that pins the
# absolute Node binary used at install time, so it keeps working regardless
# of which node (nvm version, conda, system) a later shell has on PATH.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${WAZIR_BIN_DIR:-$HOME/.local/bin}"

if [[ ! -f "$REPO_ROOT/package.json" ]] || ! grep -q '"@wazir/cli"' "$REPO_ROOT/apps/cli/package.json" 2>/dev/null; then
  echo "error: could not find the Wazir repository at $REPO_ROOT" >&2
  echo "       run this script from a Wazir checkout, e.g. bash ~/Code/Wazir/scripts/install.sh" >&2
  exit 1
fi

if [[ "$PWD" != "$REPO_ROOT" ]]; then
  echo "note: running from $PWD; switching to repository root $REPO_ROOT"
fi
cd "$REPO_ROOT"

if ! command -v node >/dev/null 2>&1; then
  echo "error: node is not installed. Wazir needs Node.js >= 20 (https://nodejs.org or nvm)." >&2
  exit 1
fi
NODE_BIN="$(command -v node)"
NODE_BIN="$(readlink -f "$NODE_BIN" 2>/dev/null || echo "$NODE_BIN")"
NODE_MAJOR="$("$NODE_BIN" -p 'process.versions.node.split(".")[0]')"
if (( NODE_MAJOR < 20 )); then
  echo "error: Node.js >= 20 required, found $("$NODE_BIN" -v) at $NODE_BIN" >&2
  exit 1
fi
echo "==> Using Node $("$NODE_BIN" -v) at $NODE_BIN"

CLI_ENTRY="$REPO_ROOT/apps/cli/dist/index.js"
BUILD_LOG="${TMPDIR:-/tmp}/wazir-install-build.log"
BUILD_STATUS="ok"

if [[ "${WAZIR_SKIP_BUILD:-0}" == "1" ]]; then
  echo "==> WAZIR_SKIP_BUILD=1: skipping npm install / build"
  BUILD_STATUS="skipped"
else
  echo "==> Installing dependencies"
  if ! npm install; then
    echo "error: npm install failed. Check your network and Node/npm setup, then re-run." >&2
    exit 1
  fi

  echo "==> Building all workspaces (log: $BUILD_LOG)"
  if ! npm run build 2>&1 | tee "$BUILD_LOG"; then
    BUILD_STATUS="failed"
    # tsc --build reports the same diagnostic once per dependent workspace with a
    # different relative path; normalise to basename+position and dedupe.
    ERRORS="$(grep -E 'error TS[0-9]+' "$BUILD_LOG" | sed -E 's#^([^(]*/)?([^/(]+)\(#\2(#' | sort -u || true)"
    ERROR_COUNT="$(printf '%s' "$ERRORS" | grep -c . || true)"
    echo
    echo "==> BUILD FAILED ($ERROR_COUNT TypeScript error(s))" >&2
    if [[ -n "$ERRORS" ]]; then
      echo "    Files with errors:" >&2
      printf '%s\n' "$ERRORS" | sed -E 's/\(.*//' | sort | uniq -c | sort -rn | sed 's/^/      /' >&2
    fi
    if ! git -C "$REPO_ROOT" diff --quiet -- packages apps 2>/dev/null || \
       [[ -n "$(git -C "$REPO_ROOT" ls-files --others --exclude-standard -- packages apps 2>/dev/null)" ]]; then
      echo "    Your working tree has uncommitted changes under packages/ or apps/ — the failure" >&2
      echo "    is most likely in that in-progress code, not in the install. Fix the errors above," >&2
      echo "    or install the last committed state with:" >&2
      echo "      git -C \"$REPO_ROOT\" stash -u && bash \"$REPO_ROOT/scripts/install.sh\" && git -C \"$REPO_ROOT\" stash pop" >&2
    fi
    echo "    Full log: $BUILD_LOG" >&2
  fi
fi

if [[ ! -f "$CLI_ENTRY" ]]; then
  echo >&2
  echo "error: no CLI build found at $CLI_ENTRY — cannot install 'wa'." >&2
  [[ "$BUILD_STATUS" == "skipped" ]] && echo "       (WAZIR_SKIP_BUILD=1 was set; run without it to build)" >&2
  exit 1
fi
if [[ "$BUILD_STATUS" == "failed" ]]; then
  echo "    A previous build exists at $CLI_ENTRY; installing the 'wa' launcher against it" >&2
  echo "    so the CLI stays usable. It does NOT include your uncommitted changes." >&2
  echo
fi

echo "==> Installing 'wa' launcher to $BIN_DIR/wa"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/wa" <<SHIM
#!/usr/bin/env bash
# Wazir CLI launcher — generated by scripts/install.sh. Re-run that script to update.
NODE_BIN="$NODE_BIN"
CLI="$CLI_ENTRY"
if [[ ! -x "\$NODE_BIN" ]]; then
  NODE_BIN="\$(command -v node || true)"
fi
if [[ -z "\$NODE_BIN" ]]; then
  echo "wa: node not found (expected $NODE_BIN). Re-run: bash $REPO_ROOT/scripts/install.sh" >&2
  exit 127
fi
if [[ ! -f "\$CLI" ]]; then
  echo "wa: Wazir build missing at \$CLI. Re-run: bash $REPO_ROOT/scripts/install.sh" >&2
  exit 127
fi
exec "\$NODE_BIN" "\$CLI" "\$@"
SHIM
chmod +x "$BIN_DIR/wa"

# Remove a stale npm-link `wa` from any nvm-managed node so it can't shadow the shim.
for stale in "$HOME"/.nvm/versions/node/*/bin/wa; do
  [[ -L "$stale" ]] && rm -f "$stale" && echo "    removed stale npm link $stale"
done

# Make sure the shim directory is on PATH for future shells.
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    PATH_LINE="export PATH=\"$BIN_DIR:\$PATH\""
    for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
      [[ -f "$rc" ]] || continue
      if ! grep -qF "$PATH_LINE" "$rc"; then
        printf '\n# Added by Wazir install\n%s\n' "$PATH_LINE" >> "$rc"
        echo "    added $BIN_DIR to PATH in $rc"
      fi
    done
    echo
    echo "NOTE: $BIN_DIR was not on your PATH. Open a new shell, or run now:"
    echo "  $PATH_LINE"
    ;;
esac

echo
if [[ "$BUILD_STATUS" == "failed" ]]; then
  echo "Done with warnings: 'wa' launcher installed against the previous build; the current source did not compile."
  echo "Re-run this script after fixing the errors to refresh the build."
  echo
else
  echo "Done."
fi
echo "Next steps (with Ollama or LM Studio running):"
echo "  wa doctor"
echo "  wa models list"
echo "  wa ask \"explain what this repository does\""

[[ "$BUILD_STATUS" == "failed" ]] && exit 2
exit 0
