#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';

const homedir = os.homedir();
const binDir = process.env.WAZIR_BIN_DIR || path.join(homedir, '.local', 'bin');
const wazirDir = process.env.WAZIR_HOME || path.join(homedir, '.wazir');
const envFile = path.join(wazirDir, '.env');
const configFile = path.join(wazirDir, 'config.json');

console.log('==> Configuring Wazir environment and configuration files...');

// 1. Ensure ~/.wazir directory exists with secure permissions (0700)
if (!existsSync(wazirDir)) {
  mkdirSync(wazirDir, { recursive: true, mode: 0o700 });
  console.log(`✓ Created Wazir config directory: ${wazirDir}`);
} else {
  try {
    chmodSync(wazirDir, 0o700);
  } catch {}
}

// 2. Ensure ~/.wazir/.env exists with secure defaults & tokens
const generateToken = () => crypto.randomBytes(32).toString('hex');

if (!existsSync(envFile)) {
  const apiToken = generateToken();
  const regToken = generateToken();
  const defaultEnv = [
    '# Wazir Meta-Harness Environment Configuration',
    '# Automatically generated by Wazir installation setup',
    '',
    '# Runtime URLs',
    'WAZIR_OLLAMA_URL=http://localhost:11434',
    'WAZIR_LMSTUDIO_URL=http://localhost:1234/v1',
    '',
    '# Networking & Host Identity',
    'PORT=4800',
    'WAZIR_HOST=127.0.0.1',
    'WAZIR_COMPUTER_ID=local',
    `WAZIR_COMPUTER_NAME=${os.hostname() || 'local-workstation'}`,
    '',
    '# Control-plane Security & Cluster Tokens',
    `WAZIR_API_TOKEN=${apiToken}`,
    `WAZIR_REGISTRATION_TOKEN=${regToken}`,
    '',
    '# Execution Sandbox (auto, bwrap, sandbox-exec, none)',
    'WAZIR_SANDBOX=auto',
    '',
  ].join('\n');

  writeFileSync(envFile, defaultEnv, { encoding: 'utf8', mode: 0o600 });
  console.log(`✓ Created environment file with generated security tokens: ${envFile}`);
} else {
  // Update existing .env with any missing security tokens or URLs
  try {
    let content = readFileSync(envFile, 'utf8');
    let modified = false;

    if (!content.includes('WAZIR_OLLAMA_URL=')) {
      content += '\nWAZIR_OLLAMA_URL=http://localhost:11434';
      modified = true;
    }
    if (!content.includes('WAZIR_LMSTUDIO_URL=')) {
      content += '\nWAZIR_LMSTUDIO_URL=http://localhost:1234/v1';
      modified = true;
    }
    if (!content.includes('WAZIR_API_TOKEN=') || content.match(/^WAZIR_API_TOKEN=\s*$/m)) {
      const token = generateToken();
      if (content.includes('WAZIR_API_TOKEN=')) {
        content = content.replace(/^WAZIR_API_TOKEN=.*$/m, `WAZIR_API_TOKEN=${token}`);
      } else {
        content += `\nWAZIR_API_TOKEN=${token}`;
      }
      modified = true;
    }
    if (!content.includes('WAZIR_REGISTRATION_TOKEN=') || content.match(/^WAZIR_REGISTRATION_TOKEN=\s*$/m)) {
      const token = generateToken();
      if (content.includes('WAZIR_REGISTRATION_TOKEN=')) {
        content = content.replace(/^WAZIR_REGISTRATION_TOKEN=.*$/m, `WAZIR_REGISTRATION_TOKEN=${token}`);
      } else {
        content += `\nWAZIR_REGISTRATION_TOKEN=${token}`;
      }
      modified = true;
    }

    if (modified) {
      writeFileSync(envFile, content, { encoding: 'utf8', mode: 0o600 });
      console.log(`✓ Updated existing environment file with missing tokens/URLs: ${envFile}`);
    } else {
      console.log(`✓ Environment file already configured: ${envFile}`);
    }
    chmodSync(envFile, 0o600);
  } catch (err) {
    console.warn(`! Warning: could not verify or update ${envFile}:`, err.message);
  }
}

// 3. Ensure ~/.wazir/config.json exists
if (!existsSync(configFile)) {
  const defaultConfig = {
    ollamaUrl: 'http://localhost:11434',
    lmstudioUrl: 'http://localhost:1234/v1',
    modelContext: {},
    modelCapabilities: {},
    networkAllowed: false,
    allowCommands: [],
    denyCommands: [],
    allowedMcpServers: [],
  };
  writeFileSync(configFile, JSON.stringify(defaultConfig, null, 2), { encoding: 'utf8', mode: 0o600 });
  console.log(`✓ Created default configuration file: ${configFile}`);
} else {
  console.log(`✓ Configuration file already exists: ${configFile}`);
}

// 4. Update Shell Profile / RC files to ensure PATH and WAZIR_HOME are available
const pathLine = `export PATH="${binDir}:$PATH"`;
const homeLine = `export WAZIR_HOME="${wazirDir}"`;

const shellFiles = [
  path.join(homedir, '.bashrc'),
  path.join(homedir, '.zshrc'),
  path.join(homedir, '.profile'),
  path.join(homedir, '.bash_profile'),
];

let updatedShellFiles = 0;
for (const shellFile of shellFiles) {
  if (!existsSync(shellFile)) continue;
  try {
    const content = readFileSync(shellFile, 'utf8');
    const needsPath = !content.includes(binDir) && !content.includes('$HOME/.local/bin') && !content.includes('${HOME}/.local/bin');
    const needsHome = !content.includes('WAZIR_HOME=');

    if (needsPath || needsHome) {
      let addition = '\n# Added by Wazir install\n';
      if (needsPath) addition += `${pathLine}\n`;
      if (needsHome) addition += `${homeLine}\n`;
      writeFileSync(shellFile, content + addition, 'utf8');
      console.log(`✓ Updated shell configuration: ${shellFile}`);
      updatedShellFiles++;
    }
  } catch (err) {
    console.warn(`! Could not update ${shellFile}:`, err.message);
  }
}

// Check fish shell if present
const fishConfig = path.join(homedir, '.config', 'fish', 'config.fish');
if (existsSync(fishConfig)) {
  try {
    const content = readFileSync(fishConfig, 'utf8');
    if (!content.includes(binDir) && !content.includes('.local/bin')) {
      const addition = `\n# Added by Wazir install\nfish_add_path ${binDir}\nset -gx WAZIR_HOME "${wazirDir}"\n`;
      writeFileSync(fishConfig, content + addition, 'utf8');
      console.log(`✓ Updated fish shell configuration: ${fishConfig}`);
      updatedShellFiles++;
    }
  } catch {}
}

// Ensure binDir exists
if (!existsSync(binDir)) {
  mkdirSync(binDir, { recursive: true });
}

console.log('✓ All environment files and shell profiles are up to date.');
